use_frameworks!

platform :ios, '10.0'

target 'SocialLoginSwift_Example' do
  pod 'SocialLoginSwift', :path => '../'
  pod 'GoogleSignIn'

  target 'SocialLoginSwift_Tests' do
    inherit! :search_paths

    
  end
end
