use_frameworks!

platform :ios, '13.0'

target 'SocialLoginSwift_Example' do
  pod 'SocialLoginSwift', :path => '../'
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'

  target 'SocialLoginSwift_Tests' do
    inherit! :search_paths

    
  end
end
